(() => {
  const row = (item, detail, overall, scope, ux, requirements, tech) => ({
    item,
    detail,
    overall,
    scope,
    ux,
    requirements,
    tech,
  });

  const phase = (label) => ({ phase: label });

  window.MANAFA_HUB_ROADMAPS = [
    {
      id: 'channel',
      title: 'Channel Hub',
      products: [
        {
          id: 'borrower',
          label: 'Borrower',
          title: 'Borrower Channel',
          owner: 'Mohammed Alghofaily',
          updated: '31 July 2026 · Jira check',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4419911696/Borrower+Channel+Product+Roadmap',
          note: 'Jira DF-3357 places Onboarding Activation Journey V2 in the delivery queue for Manafa Release 61. No R62 fix version is currently recorded.',
          rows: [
            row('Vendor ID visualization', 'Add the buyer vendor ID to the entity profile', 'Planned', 'Planned', 'Planned', 'Planned', 'Planned'),
            row('Supplier — Registration', 'Registration enhancement for different programs', 'Planned', 'Done', 'In progress', 'In progress', '—'),
            row('Supplier — Registration', 'Borrower onboarding revamp', 'Planned', 'Done', 'In progress', 'In progress', '—'),
            row('Supplier — Financing', 'Borrower financing journey revamp', 'Planned', 'Done', 'In progress', 'In progress', '—'),
            row('Supplier — Registration', 'Borrower onboarding revamp · Phase 2 · DF-3357', 'In delivery queue', 'Done', 'In progress', 'In progress', 'R61'),
            row('Supplier — Financing', 'Borrower financing journey revamp · Phase 2', 'Planned', 'Planned', '—', '—', '—'),
            row('Supplier — Registration', 'Secondary user optimization', 'Planned', 'Planned', '—', '—', '—'),
            row('Supplier — Registration', 'Nafath across all user types', 'Planned', 'Planned', '—', '—', '—'),
            row('Supplier — Taulia', 'Taulia onboarding API — receive supplier basic information', 'Planned', '—', '—', '—', '—'),
            row('Supplier — Funder Tracker', 'Funder decision tracker and fallback flow', 'Planned', 'Planned', '—', '—', '—'),
          ],
        },
        {
          id: 'funder',
          label: 'Funder',
          title: 'Funder Channel',
          owner: 'Fahad Aldossari',
          updated: '3 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4418273292/Funder+Channel+Product+Roadmap+2026',
          note: 'The source roadmap lists this initiative but leaves every delivery-stage field blank.',
          rows: [
            row('Funder sign-up', 'Funder user sign-up using email', 'Unspecified', '—', '—', '—', '—'),
          ],
        },
        {
          id: 'buyer',
          label: 'Buyer',
          title: 'Buyer Channel',
          owner: 'Mohammed Alghofaily',
          updated: '8 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4420337673/Buyer+Channel+Product+Roadmap',
          rows: [
            row('Funder Management', 'Buyer funding settings', 'Planned', 'Done', 'Done', 'Done', 'Planned'),
            row('Analytics', 'Quarter comparisons, supplier analytics and deviant-value handling', 'Planned', 'In progress', '—', '—', 'Planned'),
            row('Dashboard', 'Overall program-data dashboard', 'Planned', 'In progress', '—', '—', '—'),
            row('Calendar', 'Weekends and holidays management', 'Planned', 'In progress', '—', '—', '—'),
            row('Calendar', 'Hold financing during a time period', 'Planned', 'In progress', '—', '—', '—'),
            row('Supplier Management', 'Manual supplier addition by the buyer', 'Planned', 'In progress', '—', '—', '—'),
            row('Invoice Management', 'EP payable-details tracking', 'Planned', 'Planned', '—', '—', '—'),
            row('Reports', 'Periodic monthly and yearly email reports', 'Planned', 'Planned', '—', '—', '—'),
          ],
        },
      ],
    },
    {
      id: 'counterparty',
      title: 'Counterparty Hub',
      products: [
        {
          id: 'buyer-management',
          label: 'Buyer Management',
          title: 'Buyer Management',
          owner: 'Mohammed Alghofaily',
          updated: '8 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4420501508/Buyer+Management+Product+Roadmap',
          rows: [
            row('Buyer Profile Management', 'Buyer configuration and feature controls', 'Planned', 'In progress', 'In progress', 'In progress', '—'),
            row('Reports Management', 'Manage buyer reports and create reports on their behalf', 'Planned', '—', '—', '—', '—'),
            row('Supplier Management', 'Enable or disable suppliers from an SCF program', 'Planned', 'In progress', 'In progress', 'In progress', '—'),
            row('Supplier Management', 'Segment suppliers by wave, currency, spend, size and industry', 'Planned', 'In progress', 'In progress', 'In progress', '—'),
            row('Calendar Management', 'Weekends and holidays', 'Planned', '—', '—', '—', '—'),
            row('Calendar Management', 'Hold financing during a time period', 'Planned', '—', '—', '—', '—'),
            row('User Management', 'Manage user authorizations', 'Planned', '—', '—', '—', '—'),
            row('Payable Confirmations', 'Register confirmed payables through single or bulk upload', 'Planned', '—', '—', '—', '—'),
            row('Analytics', 'Program, supplier and payable analytics', 'Planned', '—', '—', '—', '—'),
          ],
        },
        {
          id: 'scf-finops',
          label: 'SCF FinOps',
          title: 'SCF FinOps',
          owner: 'Fahad Aldossari',
          updated: '3 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4382097412/Supply+Chain+Financing+FinOps+Product+Roadmap+2026',
          note: 'FinOps records BA and UX status separately; month values are preserved from the source table.',
          rows: [
            row('Dashboard Management', 'FinOps dashboard', 'Not started', 'Jul', 'Not started · Jul', 'Jul', '—'),
            row('Instruments Management', 'Invoices list', 'Done', 'Jun', 'Done · Jul', 'Jun', '—'),
            row('Instruments Management', 'Credit note list', 'Done', 'Jun', 'Done · Jul', 'Jun', '—'),
            row('Financing Management', 'EP list', 'Done', 'Jun', 'Done · Jul', 'Jun', '—'),
            row('Financing Management', 'Offer details', 'Done', 'Jun', 'Done · Jul', 'Jun', '—'),
            row('Financing Management', 'No-offer available attempts', 'Done', 'Jun', 'Done · Jul', 'Jun', '—'),
            row('Financing Management', 'Loans list', 'Done', 'Jun', 'In progress · Jul', 'Jun', '—'),
            row('Counterparty Management', 'Suppliers list and supplier details', 'Done', 'Jun', 'In progress · Jul', 'Jun', '—'),
            row('Counterparty Management', 'Funders', 'Not started', 'Jul', 'Not started', 'Jul', '—'),
            row('Counterparty Management', 'Buyers', 'Not started', 'Jul', 'Not started', 'Jul', '—'),
            row('Operations', 'Logs and files / documents', 'Not started', 'Jul', 'Not started', 'Jul', '—'),
            row('Operations', 'Wallets / accounts and reports', 'Not started', 'Jul', 'Not started', 'Jul', '—'),
            row('SLA', 'SLA monitor', 'In progress', 'Jun', 'Not started', 'Jun', '—'),
            row('Alerts', 'View alerts', 'In progress', 'Jun', 'Not started', 'Jun', '—'),
          ],
        },
      ],
    },
    {
      id: 'customer',
      title: 'Customer Hub',
      products: [
        {
          id: 'client-lifecycle',
          label: 'Client Lifecycle',
          title: 'Client Lifecycle Management',
          owner: 'Norah Aljmhoor',
          updated: '27 July 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4417781953/Client+Lifecycle+CLM+Product+Roadmap+2026',
          note: 'The source roadmap is phase-based. UX, requirements and technology dates remain TBD throughout.',
          rows: [
            phase('Phase 1 — CLM Foundation'),
            row('CLM Foundation', 'Navigation, header, notifications, search, site switcher and user profile', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            row('Client Registry', 'Entity, stakeholder and user profiles', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            row('Case Management', 'Case list and case workspace', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            phase('Phase 2 — Onboarding & Due Diligence'),
            row('Customer Due Diligence', 'CDD, KYC and KYB', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            row('Enhanced Due Diligence', 'Document, IBAN and signatory verification', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            row('Authorization Management', 'Authorization and delegation requests', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            phase('Phase 3 — Case Generation'),
            row('Operations Requests', 'Create, view, respond to and cancel operations requests', 'In progress', 'July', 'TBD', 'TBD', 'TBD'),
            phase('Phase 4 — Investor & Client Lifecycle'),
            row('Client Registry', 'Qualified-investor and investor profiles', 'In progress', 'August', 'TBD', 'TBD', 'TBD'),
            row('Lifecycle Management', 'Reclassification, change of circumstance and periodic review', 'To do', 'August', 'TBD', 'TBD', 'TBD'),
            phase('Phase 5 — AML & Compliance'),
            row('AML & Risk', 'AML reviews, watchlists, restrictions and high-risk users', 'To do', 'September', 'TBD', 'TBD', 'TBD'),
            row('Offboarding', 'Borrower and investor offboarding', 'To do', 'September', 'TBD', 'TBD', 'TBD'),
            phase('Phase 6 — Operations'),
            row('Dashboard & Insights', 'Executive and operations dashboards', 'To do', 'September', 'TBD', 'TBD', 'TBD'),
            row('Operations Management', 'Assignment, workload, SLA and case-health management', 'To do', 'September', 'TBD', 'TBD', 'TBD'),
          ],
        },
        {
          id: 'crm',
          label: 'CRM',
          title: 'Customer Relationship Management',
          owner: 'Mohammed Alasaker',
          updated: '3 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4407296018/Customer+Relationship+Management+CRM+Product+Roadmap+2026',
          note: 'For CRM, PO, UI/UX and BA deadlines are mapped to scope, UX and requirements.',
          rows: [
            row('Lead Management', 'Leads table and pipeline view', 'Done', '14 Jul · Done', '19 Jul · Done', '19 Jul · Done', 'R61'),
            row('Lead Management', 'Lead intake and migration rules', 'Done', '14 Jul · Done', '19 Jul · Done', '19 Jul · Done', 'R61'),
            row('Lead Management', 'Lead profile page and export', 'Done', '14 Jul · Done', '19 Jul · Done', '19 Jul · Done', 'R61'),
            row('Target Management', 'Financing and non-financial targets', 'In progress', '—', '—', '—', '—'),
            row('Target Management', 'Commissions and performance targets', 'In progress', '—', '—', '—', '—'),
            row('Target Management', 'Target view', 'In progress', '—', '—', '—', '—'),
            row('Assignee Management', 'Assignee configurations', 'Not started', '—', '—', '—', '—'),
            row('Pipeline Management', 'Pipeline view and company-profile enhancements', 'Not started', '—', '—', '—', '—'),
            row('Dashboard & Performance', 'Agent and team-level performance dashboards', 'Not started', '—', '—', '—', '—'),
          ],
        },
      ],
    },
    {
      id: 'lending',
      title: 'Lending Hub',
      products: [
        {
          id: 'funder-management',
          label: 'Funder Management',
          title: 'Funder Management',
          owner: 'Bandar Alarifi',
          updated: '8 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4221304854/Funders+Management+FMS+Product+Roadmap+2026',
          rows: [
            row('Funder Profile Management', 'Dashboard', 'Partially done', 'Pending', 'Pending', 'Pending', 'Pending'),
            row('Funder Profile Management', 'Display financed companies', 'Partially done', 'Done', 'Pending', 'Done', 'Pending · migrate'),
            row('Funder Profile Management', 'View wallet and investment details', 'Partially done', 'Done', 'Pending', 'Done', 'Pending · migrate'),
            row('Programs Management', 'View and edit programs', 'Partially done', 'Done', 'Pending', 'Done', 'Pending · migrate'),
            row('Programs Management', 'Investment parameters, eligibility and pricing', 'Partially done', 'Done', 'Pending', 'Done', 'Pending · migrate'),
            row('Programs Management', 'SCF program configurations', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending'),
            row('Programs Management', 'Move existing SCF funders to the new platform', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending'),
            row('Dashboard Management', 'Main and per-funder dashboards', 'Pending', '—', '—', '—', '—'),
            row('Users Management', 'Funder users and role-based permissions', 'Pending', '—', '—', '—', '—'),
            row('Withdrawals Management', 'Approvers, hierarchy, workflow and tracking', 'Pending', '—', '—', '—', '—'),
            row('Wallets Management', 'Create and manage wallets', 'Pending', '—', '—', '—', '—'),
          ],
        },
        {
          id: 'los',
          label: 'LOS',
          title: 'Loan Origination System',
          owner: 'Danah Alsuhaibani',
          updated: '21 July 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4453597185/LOS-+Roadmap+2026',
          rows: [
            phase('Phase 1 — LOS Foundation'),
            row('Workspace Foundation', 'Site architecture, navigation and header', 'Not started', '—', '—', '—', 'TBD'),
            phase('Phase 2 — Credit Assessment'),
            row('Borrower Management', 'Entity, related-entity, owner and group-company data', 'Not started', 'August', '—', 'August', '—'),
            row('Credit Analysis & Underwriting', 'Initial assessment, financial positioning and credit bureau', 'Not started', 'August', '—', 'Aug / Sep', '—'),
            row('Credit Scoring', 'Scoring and scoring-engine builder', 'Not started', 'TBD', '—', 'TBD', '—'),
            phase('Phase 3 — Credit Decision & Offer Letter'),
            row('Credit Committee', 'Committee management, pricing decision and voting', 'Not started', 'September', '—', 'September', '—'),
            row('Offer Letter', 'Offer-letter management', 'Not started', 'September', '—', 'September', '—'),
            phase('Phase 4 — Contract Management'),
            row('Contract Management', 'Facility contracts, PN management and guarantors', 'Not started', 'September', '—', 'September', '—'),
            phase('Phase 5 — Disbursement Activities'),
            row('Disbursement Orchestration', 'Product enablement, fund requests and loan creation', 'Not started', 'October', '—', 'October', '—'),
          ],
        },
        {
          id: 'lms',
          label: 'LMS',
          title: 'Loan Management System',
          owner: 'Danah Alsuhaibani',
          updated: '21 July 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4453564425/LMS-+Roadmap+2026',
          rows: [
            phase('Phase 1 — LMS Foundation & Borrower Account Onboarding'),
            row('Workspace Foundation', 'Site architecture, navigation, header and user home', 'Not started', '—', 'TBD', '—', 'TBD'),
            row('Borrower Management', 'Borrower, related-company and utilization views', 'Not started', 'August', '—', 'August', '—'),
            phase('Phase 2 — Loan Onboarding'),
            row('Loan Account Management', '360° loan view, fund requests, opportunities and history', 'Not started', 'October', '—', 'October', '—'),
            phase('Phase 3 — Beneficiary & Document Management'),
            row('Beneficiary & Documents', 'Beneficiary classification and document organization', 'Not started', 'September', '—', 'September', '—'),
            phase('Phase 4 — Transaction & Payment Monitoring'),
            row('Payment Management', 'Payment monitoring, holiday calendar and reminders', 'Not started', 'September', '—', 'September', '—'),
            phase('Phase 5 — Case & Recovery Management'),
            row('Case Management', 'Case details, promise-to-pay and case workflow', 'Not started', 'November', '—', 'November', '—'),
            row('Recovery Management', 'Recovered funds and recovery strategies', 'Not started', 'Nov / TBD', '—', 'Nov / TBD', '—'),
          ],
        },
        {
          id: 'collections',
          label: 'Collections',
          title: 'Collections Management System',
          owner: 'Alma Alfowzan',
          updated: '3 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4420567041/Collections+Management+Systems+CMS+Product+Roadmap+2026',
          note: 'The source roadmap is marked Pending and contains no defined delivery rows.',
          rows: [],
        },
      ],
    },
    {
      id: 'finance',
      title: 'Finance Hub',
      products: [
        {
          id: 'invoice-management',
          label: 'Invoice Management',
          title: 'Invoice Management',
          owner: 'Bandar Alarifi',
          updated: '8 June 2026',
          source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4413423622/Invoice+Management+Systems+IMS+Product+Roadmap+2026',
          rows: [
            row('Billing Engine', 'Auto invoicing for borrowers and investors', 'Done', 'Done', 'Done', 'Done', 'Done'),
            row('Invoice Management', 'Invoice master list and filtering', 'Done', 'Done', 'Done', 'Done', 'Done'),
            row('Invoice Management', 'Invoice detail view, dashboard and borrower invoice creation', 'Done', 'Done', 'Done', 'Done', 'Done'),
            row('Invoice Management', 'Issue credit note / refund', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Customer Management', 'Customer registry', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Customer Management', 'Create customer invoice', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Compliance & ZATCA', 'Submission engine and status tracking', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Compliance & ZATCA', 'Credit-note submission to ZATCA', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Document Rendering', 'B2B and B2C invoice redesign', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Document Rendering', 'Credit-note and credit-debt documents', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Borrower Invoice Experience', 'Invoice detail, unified list and downloads', 'In progress', 'Done', 'Done', 'Done', 'In progress'),
            row('Tax Declaration', 'Support Finance in submitting the declaration to ZATCA', 'To do', '—', '—', '—', '—'),
          ],
        },
      ],
    },
  ];

  const counterpartyHub = window.MANAFA_HUB_ROADMAPS.find((hub) => hub.id === 'counterparty');
  const lendingHub = window.MANAFA_HUB_ROADMAPS.find((hub) => hub.id === 'lending');
  const funderManagementIndex = lendingHub.products.findIndex((product) => product.id === 'funder-management');
  const [funderManagement] = lendingHub.products.splice(funderManagementIndex, 1);

  counterpartyHub.products = [
    counterpartyHub.products.find((product) => product.id === 'scf-finops'),
    counterpartyHub.products.find((product) => product.id === 'buyer-management'),
    funderManagement,
  ];

  const customerHub = window.MANAFA_HUB_ROADMAPS.find((hub) => hub.id === 'customer');
  customerHub.products.push({
    id: 'customer-service',
    label: 'Customer Service',
    title: 'Customer Service Platform',
    owner: 'Not assigned in source',
    updated: 'No roadmap page found',
    source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
    note: 'The platform is defined in the suite strategy, but no delivery roadmap was found in Product Team Spaces.',
    rows: [],
  });

  const financeHub = window.MANAFA_HUB_ROADMAPS.find((hub) => hub.id === 'finance');
  financeHub.products.push(
    {
      id: 'ledger',
      label: 'Ledger',
      title: 'Ledger Platform',
      owner: 'Not assigned in source',
      updated: 'No roadmap page found',
      source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
      note: 'The platform is defined in the suite strategy, but no delivery roadmap was found in Product Team Spaces.',
      rows: [],
    },
    {
      id: 'treasury',
      label: 'Treasury',
      title: 'Treasury Platform',
      owner: 'Not assigned in source',
      updated: 'No roadmap page found',
      source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
      note: 'The platform is defined in the suite strategy, but no delivery roadmap was found in Product Team Spaces.',
      rows: [],
    },
  );

  window.MANAFA_HUB_ROADMAPS.push({
    id: 'embedded',
    title: 'Embedded Hub',
    products: [
      {
        id: 'developer-platform', label: 'Developer Platform', title: 'Developer Platform',
        owner: 'Not assigned in source', updated: 'No roadmap page found',
        source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
        note: 'The capability is shown in the target product structure; a delivery roadmap was not found in Product Team Spaces.', rows: [],
      },
      {
        id: 'api-gateway', label: 'API Gateway', title: 'API Gateway',
        owner: 'Not assigned in source', updated: 'No roadmap page found',
        source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
        note: 'The capability is shown in the target product structure; a delivery roadmap was not found in Product Team Spaces.', rows: [],
      },
      {
        id: 'api-middleware', label: 'API Middleware', title: 'API Middleware',
        owner: 'Not assigned in source', updated: 'No roadmap page found',
        source: 'https://manafaco.atlassian.net/wiki/spaces/PTS/pages/4333600819/Manafa+Business+Suite+Strategy',
        note: 'The capability is shown in the target product structure; a delivery roadmap was not found in Product Team Spaces.', rows: [],
      },
    ],
  });
})();
